# fly.toml app configuration file generated for end-to-end-meeting-notes-automator on 2025-04-16T12:52:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'end-to-end-meeting-notes-automator'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
