app = "end-to-end-meeting-notes-automator"  # Replace with your actual app name from `fly launch`
primary_region = "ams"  # Example: Amsterdam; use one near your users (run `fly regions list`)

[build]
  image = "registry.fly.io/end-to-end-meeting-notes-automator"

[env]
  # Environment variables can be set here or using `fly secrets set`
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[http_service.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
